# Generated by Django 4.1.7 on 2023-02-18 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="follower",
        ),
        migrations.CreateModel(
            name="EventFollower",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="event.event"
                    ),
                ),
                (
                    "id_follower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="event.follower"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="event",
            name="follower",
            field=models.ManyToManyField(
                blank=True, through="event.EventFollower", to="event.follower"
            ),
        ),
    ]
