# Generated by Django 4.1.7 on 2023-02-18 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('time',)},
        ),
        migrations.AlterField(
            model_name='event',
            name='follower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='event.follower', verbose_name='Подписчик события'),
        ),
    ]
